# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LSVCMM <- function(response, subject, response_time, vcm_covariates, fixed_covariates, offset, family_name, link, kernel_name, estimated_time, kernel_scale, n_kernel_scale, penalize_intercept, alpha, adaptive, lambda, lambda_factor, n_lambda, working_covariance, estimate_variance_components, variance_ratio, max_rounds, max_iter, rel_tol, verbose, update_method) {
    .Call(`_LSVCMM_LSVCMM`, response, subject, response_time, vcm_covariates, fixed_covariates, offset, family_name, link, kernel_name, estimated_time, kernel_scale, n_kernel_scale, penalize_intercept, alpha, adaptive, lambda, lambda_factor, n_lambda, working_covariance, estimate_variance_components, variance_ratio, max_rounds, max_iter, rel_tol, verbose, update_method)
}

